##################################################################################################
# httpbin2022 service running on port 8080 inside the container. Ingress is still port 80
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin2022
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin2022
  labels:
    app: httpbin2022
    service: httpbin2022
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: httpbin2022
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin2022
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin2022
      version: v1
  template:
    metadata:
      labels:
        app: httpbin2022
        version: v1
    spec:
      serviceAccountName: httpbin2022
      containers:
      - image: docker.io/mshanley80/httpbin2022
        imagePullPolicy: IfNotPresent
        name: httpbin2022
        ports:
        - containerPort: 8080
        env:
        # This tells httpbin to run on 8080 in the container
        - name: PORT
          value: "8080"
        # This tells httpbin bind to 0.0.0.0 in the container.
        # This is the default binding, but is shown here just for an example.
        - name: HOST
          value: "0.0.0.0"


