##################################################################################################
# httpbin2022 service running on port 80 inside the container, with port 80 exposed on the host
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin2022
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin2022
  labels:
    app: httpbin2022
    service: httpbin2022
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: httpbin2022
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin2022
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin2022
      version: v1
  template:
    metadata:
      labels:
        app: httpbin2022
        version: v1
    spec:
      serviceAccountName: httpbin2022
      containers:
      - image: docker.io/mshanley80/httpbin2022
        imagePullPolicy: IfNotPresent
        name: httpbin2022
        ports:
        - containerPort: 80
